### ISSUE TITLE
Run video_stable_diffusion_vsd_guidance.py

### ISSUE THREAD

**Issue by LI-Yiquan** [sherwinbahmani/tc4d#6]
Thanks for the cool work!

Have you tried using video stable diffusion model for vsd guidance? I find video_stable_diffusion_vsd_guidance.py in the repo but I' m not sure how to run it. Thanks!

**Comment by sherwinbahmani** [comment]
Hi,

Yeah we tried SVD and it did not work well. The memory requirements are pretty high and it also never got as good results as with VideoCrafter. But I left the SVD code here:

https://github.com/sherwinbahmani/tc4d/blob/main/threestudio/models/guidance/svd_guidance.py

You need to change the part in the config here to "svd-guidance":

https://github.com/sherwinbahmani/tc4d/blob/f3a96d07e5322d7475cd0e20f97131105022b01b/configs/tc4d_stage_3.yaml#L202

Specifically you can try this as a starting point, and tune the guidance scale parameters. low_ram_vae needs to be adjusted based on how much memory you have:

```
guidance_type_video: "svd-guidance"
guidance_video:
  pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid"
  weighting_strategy: sds
  low_ram_vae: 4
  min_guidance_scale: 33.33333
  max_guidance_scale: 100.0
  width: 1024
  height: 576
```
